version: '3.4'

services:
  # addbblab5:
  #   image: addbblab5
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - "mysql"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090


