version: '3.4'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
  mysql_exporter:
    image: prom/mysqld-exporter:latest
    ports:
      - 9104:9104
    environment:
      DATA_SOURCE_NAME: "root:admin@(mysql:3306)/"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

volumes:
  prometheus-data: